// ALL user-facing strings live here and are linted against the banned
// platform-jargon list (CLAUDE.md invariant 7; UX §11). Plain, active,
// confident — a competent colleague.

export const STRINGS = {
  appName: "Engine",

  nav: {
    overview: "Overview",
    products: "Products",
    activity: "Activity",
    settings: "Settings",
    addProduct: "+ Add product",
    addShort: "+ Add",
  },

  pageIntro: {
    products: "Everything you're advertising, in one place.",
    activity: "Every move the engine makes, in plain words — tap \u201cwhy\u201d for the evidence.",
    settings: "Where ads show, how results are counted, and the limits the engine can never cross.",
  },

  headline: {
    running: "Everything is running.",
    learning: "Learning what works.",
    needs_attention: "Something needs your attention.",
    empty: "No products yet. Add one to start.",
  },

  counts: {
    products: (n: number): string => `${n} product${n === 1 ? "" : "s"}`,
    learning: (n: number): string => `${n} learning`,
    attention: (n: number): string => `${n} need${n === 1 ? "s" : ""} attention`,
  },

  kpi: {
    spend: "Spend · 7 days",
    results: "Results · 7 days",
    netReturn: "Return on total cost",
    runningCost: "Running cost · 7 days",
    runningCostHint: "What it costs to create and manage your ads",
    incremental: "Incremental return",
    incrementalPending: "Measuring — ready in a few weeks",
    noData: "No data yet",
  },

  attention: {
    title: "Needs attention",
    fix: "Fix",
    review: "Review",
    resolved: "Done",
  },

  checklist: {
    title: "Get set up",
    intro: "A few quick steps and the engine can take it from there.",
    accounts: "Connect the places your ads will show",
    site: "Add your website so results are counted",
    brandKit: "Add your brand look (logo and colors)",
    guardrails: "Review your spending limits",
    open: "Open settings",
    addFirst: "Add your first product",
    dismiss: "Hide this",
    done: "Done",
  },

  status: {
    draft: "Draft",
    in_review: "In review",
    launching: "Launching",
    learning: "Learning",
    autonomous: "Autonomous",
    needs_attention: "Needs attention",
    paused: "Paused",
  } as Record<string, string>,

  statusNote: {
    learning: "Gathering enough results to optimize reliably.",
    launching: "Setting up your ads — this takes a minute.",
    paused: "Paused. Nothing is being spent.",
    in_review: "Submitted — we'll email you when your ads are approved.",
  } as Record<string, string>,

  product: {
    funnelTitle: "Funnel — last 7 days",
    activityTitle: "What the engine did",
    why: "why",
    pause: "Pause",
    pauseHint: "Stops spending within minutes. Everything is kept, so you can resume any time.",
    resume: "Resume",
    adjust: "Adjust goal & budget",
    spent: "spent",
    running: "running",
    netShort: "net",
    buys: (n: number): string => `${n} ${n === 1 ? "buy" : "buys"}`,
    leads: (n: number): string => `${n} ${n === 1 ? "enquiry" : "enquiries"}`,
    showsOn: "Shows on",
    perDay: "Per day",
    goal: "Goal",
    save: "Save",
    cancel: "Cancel",
    marginLabel: "Profit kept per sale (%)",
    marginHint: "If set, returns count your profit, not the full sale amount.",
    empty: "Nothing here yet. The engine will narrate what it does as it works.",
  },

  ads: {
    title: "Your ads",
    empty: "No ads yet.",
    winningLine: (hook: string, pct: number): string =>
      `${hook} openings are winning right now \u2014 about ${pct}% of recent results trace back to ads that start that way.`,
    hook: {
      curiosity: "Curiosity",
      social_proof: "Social proof",
      benefit: "Benefit-led",
      contrarian: "Against the grain",
      urgency: "Urgency",
      sensory: "Look & feel",
      uploaded: "Your upload",
    } as Record<string, string>,
    adStatus: {
      ready: "Ready",
      held: "Resting",
      launched: "Live",
      retired: "Retired",
      blocked: "Held back",
      expired: "Expired",
      generating: "Being made",
    } as Record<string, string>,
    fatigue: {
      fresh: "Fresh",
      tiring: "Tiring",
      fatigued: "Tired \u2014 due for a refresh",
    } as Record<string, string>,
    promise: (pct: number): string => `${pct}% promise`,
    honestyNote:
      "Results are counted per product; the engine rests tiring ads and puts more behind what wins.",
  },

  funnelStage: {
    ViewContent: "Views",
    AddToCart: "Add to cart",
    InitiateCheckout: "Checkout started",
    Purchase: "Purchases",
    Lead: "Enquiries",
    CompleteRegistration: "Sign-ups",
    Install: "Installs",
    ClosedLead: "Closed deals",
  } as Record<string, string>,

  goals: {
    best: "We'll choose the best",
    more_sales: "More sales",
    more_enquiries: "More enquiries",
    more_bookings: "More bookings",
    more_app_installs: "More app installs",
    more_website_visits: "More website visits",
  } as Record<string, string>,

  activity: {
    title: "Activity",
    empty: "Nothing yet. As the engine works, every move it makes shows up here.",
    filterAll: "Everything",
    filterBudget: "Budget",
    filterCreative: "Ads",
    filterStatus: "Status",
    filterCheck: "Checks",
    predicted: "Expected",
    actual: "What happened",
    proposed: "Proposed (not applied)",
    blocked: "Held back by your limits",
  },

  settings: {
    title: "Settings",
    connections: "Connected accounts",
    connectionOk: "Connected",
    connectionTest: "Test mode",
    connectionTestHint:
      "Running on practice data — no real account is linked and no money is spent. Add real credentials to go live.",
    connectionProblem: "Needs reconnecting",
    notConnected: "Not connected",
    reconnect: "Reconnect",
    connect: "Connect",
    connectTitle: (name: string): string => `Connect ${name}`,
    connectIntro: "Here's what happens when you connect:",
    connectStep1:
      "Fill in the account details below. They're stored safely on your server and shown only as \u00b7\u00b7\u00b7\u00b7 last digits after saving.",
    connectStep2:
      "The engine checks the link and billing are healthy, and keeps re-checking every few hours. The status here updates automatically.",
    connectStep3:
      "Once your developer flips this channel to live, ads run on the real account you named below and results flow back automatically.",
    connectTestNote:
      "Until then this channel runs in test mode: everything works end to end on practice data and no money is spent.",
    connectSave: "Save connection",
    connectSavedNote: "Saved. Leave a field blank to keep what's stored.",
    connectMissing: "Please fill in every field marked required.",
    connectAccount: (ref: string): string => `Account ${ref}`,
    connectClose: "Got it",
    connectFieldLabels: {
      "meta.access_token": "Access key",
      "meta.ad_account_id": "Ad account number",
      "meta.dataset_id": "Measurement ID",
      "google.developer_token": "Developer key",
      "google.customer_id": "Customer number",
      "google.oauth_client_id": "Sign-in client ID",
      "google.oauth_client_secret": "Sign-in client secret",
      "google.refresh_token": "Sign-in refresh key",
      "tiktok.access_token": "Access key",
      "tiktok.advertiser_id": "Advertiser number",
      "tiktok.pixel_code": "Measurement code",
      "snapchat.access_token": "Access key",
      "snapchat.ad_account_id": "Ad account number",
      "snapchat.pixel_id": "Measurement ID",
      "pinterest.access_token": "Access key",
      "pinterest.ad_account_id": "Ad account number",
    } as Record<string, string>,
    connectFieldHelp: {
      "meta.ad_account_id":
        "Which exact ad account your ads and billing run under \u2014 in Meta Ads Manager it starts with act_.",
      "meta.dataset_id": "Meta Events Manager \u2192 your data source's ID.",
      "meta.access_token": "A long-lived system access key from Meta Business settings.",
      "google.customer_id":
        "Which exact Google Ads account to use \u2014 the xxx-xxx-xxxx number at the top right of Google Ads.",
      "tiktok.advertiser_id":
        "Which exact advertiser account \u2014 shown in TikTok Ads Manager under your business name.",
      "tiktok.pixel_code": "TikTok Events Manager \u2192 your web events code.",
      "snapchat.ad_account_id":
        "Which exact ad account \u2014 Snapchat Ads Manager \u2192 Account settings.",
      "snapchat.pixel_id": "Snapchat Events Manager \u2192 your web events ID.",
      "pinterest.ad_account_id":
        "Which exact ad account \u2014 Pinterest Ads \u2192 Account overview.",
      "ai.api_key": "From your AI provider's dashboard (kept on your server, shown only masked).",
      "ai.model": "Optional \u2014 a specific model name; a sensible default is used otherwise.",
      "ai.base_url": "Only for Llama-style hosts: the address of your compatible server.",
      "ai.mode":
        "Test writes practice copy for free. Live uses your key for real writing and decisions.",
    } as Record<string, string>,
    aiName: "AI writing & decisions",
    aiFieldLabels: {
      provider: "Provider",
      api_key: "API key",
      model: "Model (optional)",
      base_url: "Server address (Llama hosts)",
      mode: "How to run",
    } as Record<string, string>,
    aiProviders: {
      anthropic: "Anthropic (Claude)",
      openai: "OpenAI",
      deepseek: "DeepSeek",
      llama: "Llama (compatible host)",
    } as Record<string, string>,
    aiModeChoices: { test: "Test \u2014 practice copy, free", live: "Live \u2014 use my key" } as Record<string, string>,
    tracking: "Results tracking",
    trackingHint: "How reliably your sites tell us what's working.",
    trackingReady: "Reporting well",
    trackingPartial: "Partial — some results can't be tied to their ads",
    trackingPoor: "Weak — connect your site so we can see what's working",
    guardrails: "Spending limits",
    guardrailsHint:
      "Hard limits the engine can never cross. Saved when you click away; they apply to every decision immediately.",
    globalCap: "Daily limit across everything",
    perProductCap: "Daily limit per product",
    maxStep: "Biggest single change",
    killSwitch: "Stop everything",
    killSwitchHint: "Halts all spending and activity immediately. You can turn it back on any time.",
    killSwitchOn: "Stopped — nothing is being spent",
    killSwitchOff: "Running normally",
    brandKit: "Default brand",
    brandKitHint:
      "The starting brand for new pages. Every product page can carry its own brand \u2014 set it when you create the page or on the product's page later.",
    brandLogo: "Logo address",
    brandColor: "Main color",
    brandFont: "Font",
    brandTone: "Tone in one line",
    autonomy: "Autonomy",
    autonomyHint:
      "Each product starts careful and switches to automatic budget decisions once it has enough reliable results.",
    autonomyOn: "Automatic",
    autonomyWaiting: "Building up data",
    signoffQueue: "Waiting for your approval",
    signoffApprove: "Approve",
    signoffEmpty: "Nothing waiting for approval.",
    save: "Save",
    saved: "Saved",
  },

  aiManager: {
    title: "AI manager",
    hint: "Once a day the AI reviews everything \u2014 spend, results, returns on every channel \u2014 and proposes budget changes, pauses, resumes and new rules. It can only act inside your spending limits, every move is written to Activity, and the stop-everything switch halts it like everything else.",
    enabled: "Review the account daily",
    auto: "Act within my limits",
    autoOff: "Propose only \u2014 I approve in Activity",
    runNow: "Review now",
    running: "Reviewing\u2026",
    ranLine: (proposed: number, executed: number, notes: number): string =>
      `Done \u2014 ${proposed} proposal${proposed === 1 ? "" : "s"}, ${executed} applied, ${notes} note${notes === 1 ? "" : "s"}. Details are in Activity.`,
    needsAi:
      "Connect an AI provider above (or run in test mode) \u2014 the review uses it to reason about your account.",
  },

  rules: {
    title: "Your rules",
    hint: "Your own automatic actions, checked every few minutes. They obey your spending limits and the stop-everything switch, and every action they take shows up in Activity.",
    name: "Name",
    metric: "Watch",
    metrics: {
      spend: "Spend",
      results: "Results",
      cost_per_result: "Cost per result",
      net_return: "Money back per cost",
    } as Record<string, string>,
    window: "Over the last",
    windowDays: (n: number): string => (n === 1 ? "1 day" : `${n} days`),
    comparator: "When it",
    comparators: { gt: "goes above", lt: "falls below" } as Record<string, string>,
    threshold: "Limit",
    action: "Then",
    actions: { pause: "Pause it", resume: "Resume it", notify: "Tell me" } as Record<string, string>,
    scope: "Applies to",
    scopeAll: "Everything",
    add: "Add rule",
    remove: "Remove",
    on: "On",
    off: "Off",
    empty: "No rules yet. Add one and the engine checks it every few minutes.",
    cooldownHint: "After a rule acts, it waits a day before acting on the same thing again.",
    sentence: (metric: string, windowLabel: string, comparator: string, threshold: string, action: string): string =>
      `When ${metric.toLowerCase()} over the last ${windowLabel} ${comparator} ${threshold}, ${action.toLowerCase()}.`,
  },

  platformNames: {
    meta: "Instagram & Facebook",
    google: "Google",
    tiktok: "TikTok",
    snapchat: "Snapchat",
    pinterest: "Pinterest",
  } as Record<string, string>,

  common: {
    loading: "Loading…",
    currency: "AED",
    themeToDark: "Switch to dark look",
    themeToLight: "Switch to light look",
  },

  unlock: {
    title: "Enter your access key",
    hint: "This screen is protected. Paste the access key you were given to continue.",
    submit: "Continue",
  },

  sitesSection: {
    title: "Connected sites",
    hint: "Sites that report results to the engine.",
    addLabel: "Site name",
    addButton: "Add site",
    addHint:
      "You'll get a key and a one-line snippet to paste into your site. Results start appearing here within minutes of installing it.",
    typeLabel: "What kind of site?",
    typeCustom: "Any website",
    typeShopify: "Shopify",
    typeWordpress: "WordPress",
    installCustom: "Add this one line to every page, just before </head>:",
    installShopify1:
      "In Shopify: Online Store \u2192 Themes \u2192 \u22ef \u2192 Edit code \u2192 theme.liquid \u2014 paste this line just before </head> (counts visits and carries ad details through):",
    installShopify2:
      "Then: Settings \u2192 Customer events \u2192 add a custom block and paste this, so completed checkouts are counted as purchases:",
    installWordpress:
      "In WordPress: Appearance \u2192 Theme file editor \u2192 header.php \u2014 paste this line just before </head> (or use any \u201cinsert headers\u201d plugin):",
    keyNotice: "Copy this key now — it won't be shown again.",
    snippetNotice: "Then add this one line to your site, and results start flowing:",
    empty: "No sites yet. Add one to start measuring results.",
    signalTitle: "Signal strength",
    signalStrong: "Strong — results carry rich detail",
    signalOk: "OK — could be stronger",
    signalWeak: "Weak — add more detail so results connect to ads",
    signalTip:
      "Send what you know with each result (email, phone, name — securely scrambled). Richer detail means the channels find more of your buyers.",
  },

  // Creation flow — FLOW §12 strings, used verbatim (binding).
  creation: {
    addTitle: "Add something to advertise",
    addSubtitle: "Paste a link, describe it, or add a list.",
    inputPlaceholder: "Paste a link · or type what you sell…",
    wayLink: "Paste a link",
    wayDescribe: "Describe it",
    wayList: "Add a list",
    listHint: "A spreadsheet or product file, or connect your store.",
    goalLabel: "What do you want from this?",
    goalDefault: "We'll choose the best",
    budgetLabel: "How much per day?",
    budgetDefault: "We'll suggest",
    continue: "Continue",
    reading: "Reading that…",
    linkFailed: "We couldn't open that link. Tell us what you sell instead.",
    fileFailed: "We couldn't read that file. You can describe what you sell, or connect your store instead.",
    disambiguation: "Is this closer to selling a product, or offering a service?",
    disambiguationProduct: "Selling a product",
    disambiguationService: "Offering a service",
    reviewTitle: "Here's the plan",
    reassurance: "We'll start small and put more money behind whatever works.",
    lowBudgetNote:
      "Below about AED 150 a day it's harder for us to learn what works, so results may be slower.",
    yourAds: "Your ads",
    understoodAs: "Understood as",
    understoodKinds: {
      ecommerce: "A product people buy online",
      lead_generation: "A service people enquire about",
      app: "An app people install",
      subscription: "A subscription people sign up for",
      booking: "Something people book",
    } as Record<string, string>,
    understoodWrong: "Not right? Choose:",
    understoodProduct: "It's a product",
    understoodService: "It's a service",
    selectHint: "Tap an ad to keep or drop it. Only the highlighted ones go live.",
    selectedCount: (n: number, total: number): string => `${n} of ${total} will go live.`,
    editWordsShort: "Edit",
    uploadButton: "+ Add your own photos or videos",
    uploadHint:
      "PNG, JPG or WebP up to 3MB \u2014 or MP4/WebM video up to 25MB. Uploads go live alongside the made-for-you ads.",
    uploadFailed:
      "That file couldn't be added. PNG, JPG, WebP up to 3MB, or MP4/WebM up to 25MB.",
    videoBadge: "Video",
    videoNote:
      "Tall video versions are made automatically \u2014 short video is what works best on TikTok and Snapchat.",
    optimizeNote:
      "After launch, the engine shifts budget toward the ads that perform best and rests the ones that tire.",
    brandTitle: "Brand for this page",
    brandHint:
      "Each page carries its own brand \u2014 logo, color and voice. Leave blank to use your default brand from Settings.",
    formatTabs: {
      "1:1": "Square",
      "9:16": "Tall",
      "16:9": "Wide",
    } as Record<string, string>,
    creativeHelp: (n: number): string => `We made ${n}. Keep all, or pick your favorites.`,
    makeNew: "Make new ones",
    editWords: "Change the words",
    preLaunchReassurance: "You can pause or change anything later.",
    launch: "Launch",
    goalLine: "Goal",
    showsOnLine: "Shows on",
    perDayLine: "Per day",
    perDaySuggested: "(suggested)",
    peopleGoToLine: "People go to",
    choose: "Choose",
    connectNote: (name: string): string => `Connect to use ${name}`,
    destinationQuestion: "When someone taps your ad, where should they go?",
    destWebsite: "My website or page",
    destWebsiteHint: "(paste the link)",
    destHostedPage: "A simple page we make for you",
    destHostedForm: "A form we make for you",
    destHostedFormHint: "(collect enquiries)",
    destWhatsapp: "WhatsApp",
    destWhatsappHint: "(chat with you)",
    destCall: "Call you",
    destCallHint: "(tap to call)",
    destHardToMeasure: "Results here are harder to measure precisely; we still track what we can.",
    useThis: "Use this",
    noAccount: "First, choose where to advertise.",
    restrictedNotice:
      "Ads for financial services need a quick check before they go live. We'll handle it and let you know when they're approved — usually within a day.",
    submitForReview: "Submit for review",
    settingUp: "Setting up your ads — this takes a minute.",
    confirmTitle: "You're live.",
    confirmBody: "We're showing your ads and learning what works. You don't need to do anything.",
    reassuranceSmall: "We start small and put more behind what works.",
    spendReassurance: (currency: string, cap: number): string =>
      `We'll never spend more than ${currency} ${cap} a day.`,
    reassuranceTell: "We'll tell you only if we need you.",
    reassurancePause: "You can pause anytime.",
    seeHow: "See how it's doing",
    submittedTitle: "Submitted for review",
    submittedBody: "Submitted — we'll email you when your ads are approved.",
    catalogConfirm: (n: number, currency: string, amount: number): string =>
      `We found ${n} products. We'll advertise them together and show each person the ones they're most likely to buy. About ${currency} ${amount} a day across all of them.`,
    planSentence: (
      title: string,
      goalVerb: string,
      platforms: string,
      currency: string,
      perDay: number,
    ): string =>
      `We'll advertise your ${title} to people likely to ${goalVerb}, on ${platforms}, for about ${currency} ${perDay} a day. We'll start small and put more money behind whatever works.`,
    goalVerbs: {
      best: "respond",
      more_sales: "buy it",
      more_enquiries: "get in touch",
      more_bookings: "book",
      more_app_installs: "install the app",
      more_website_visits: "visit",
    } as Record<string, string>,
  },
};
