// ALL user-facing strings live here and are linted against the banned
// platform-jargon list (CLAUDE.md invariant 7; UX §11). Plain, active,
// confident — a competent colleague.

export const STRINGS = {
  appName: "Engine",

  nav: {
    overview: "Overview",
    products: "Products",
    activity: "Activity",
    settings: "Settings",
    addProduct: "+ Add product",
    addShort: "+ Add",
  },

  headline: {
    running: "Everything is running.",
    learning: "Learning what works.",
    needs_attention: "Something needs your attention.",
    empty: "No products yet. Add one to start.",
  },

  counts: {
    products: (n: number): string => `${n} product${n === 1 ? "" : "s"}`,
    learning: (n: number): string => `${n} learning`,
    attention: (n: number): string => `${n} need${n === 1 ? "s" : ""} attention`,
  },

  kpi: {
    spend: "Spend · 7 days",
    results: "Results · 7 days",
    netReturn: "Return on total cost",
    runningCost: "Running cost · 7 days",
    runningCostHint: "What it costs to create and manage your ads",
    incremental: "Incremental return",
    incrementalPending: "Measuring — ready in a few weeks",
    noData: "No data yet",
  },

  attention: {
    title: "Needs attention",
    fix: "Fix",
    review: "Review",
    resolved: "Done",
  },

  status: {
    draft: "Draft",
    in_review: "In review",
    launching: "Launching",
    learning: "Learning",
    autonomous: "Autonomous",
    needs_attention: "Needs attention",
    paused: "Paused",
  } as Record<string, string>,

  statusNote: {
    learning: "Gathering enough results to optimize reliably.",
    launching: "Setting up your ads — this takes a minute.",
    paused: "Paused. Nothing is being spent.",
    in_review: "Submitted — we'll email you when your ads are approved.",
  } as Record<string, string>,

  product: {
    funnelTitle: "Funnel — last 7 days",
    activityTitle: "What the engine did",
    why: "why",
    pause: "Pause",
    resume: "Resume",
    adjust: "Adjust goal & budget",
    spent: "spent",
    running: "running",
    netShort: "net",
    buys: (n: number): string => `${n} ${n === 1 ? "buy" : "buys"}`,
    leads: (n: number): string => `${n} ${n === 1 ? "enquiry" : "enquiries"}`,
    showsOn: "Shows on",
    perDay: "Per day",
    goal: "Goal",
    save: "Save",
    cancel: "Cancel",
    empty: "Nothing here yet. The engine will narrate what it does as it works.",
  },

  funnelStage: {
    ViewContent: "Views",
    AddToCart: "Add to cart",
    InitiateCheckout: "Checkout started",
    Purchase: "Purchases",
    Lead: "Enquiries",
    CompleteRegistration: "Sign-ups",
    Install: "Installs",
  } as Record<string, string>,

  goals: {
    best: "We'll choose the best",
    more_sales: "More sales",
    more_enquiries: "More enquiries",
    more_bookings: "More bookings",
    more_app_installs: "More app installs",
    more_website_visits: "More website visits",
  } as Record<string, string>,

  activity: {
    title: "Activity",
    empty: "Nothing yet. As the engine works, every move it makes shows up here.",
    filterAll: "Everything",
    filterBudget: "Budget",
    filterCreative: "Ads",
    filterStatus: "Status",
    filterCheck: "Checks",
    predicted: "Expected",
    actual: "What happened",
    proposed: "Proposed (not applied)",
    blocked: "Held back by your limits",
  },

  settings: {
    title: "Settings",
    connections: "Connected accounts",
    connectionOk: "Connected",
    connectionProblem: "Needs reconnecting",
    notConnected: "Not connected",
    reconnect: "Reconnect",
    connect: "Connect",
    tracking: "Results tracking",
    trackingHint: "How reliably your sites tell us what's working.",
    trackingReady: "Reporting well",
    trackingPartial: "Partial — some results can't be tied to their ads",
    trackingPoor: "Weak — connect your site so we can see what's working",
    guardrails: "Spending limits",
    guardrailsHint: "Hard limits the engine can never cross.",
    globalCap: "Daily limit across everything",
    perProductCap: "Daily limit per product",
    maxStep: "Biggest single change",
    killSwitch: "Stop everything",
    killSwitchHint: "Halts all spending and activity immediately. You can turn it back on any time.",
    killSwitchOn: "Stopped — nothing is being spent",
    killSwitchOff: "Running normally",
    brandKit: "Brand kit",
    brandLogo: "Logo address",
    brandColor: "Main color",
    brandFont: "Font",
    brandTone: "Tone in one line",
    autonomy: "Autonomy",
    autonomyHint:
      "Each product starts careful and switches to automatic budget decisions once it has enough reliable results.",
    autonomyOn: "Automatic",
    autonomyWaiting: "Building up data",
    signoffQueue: "Waiting for your approval",
    signoffApprove: "Approve",
    signoffEmpty: "Nothing waiting for approval.",
    save: "Save",
    saved: "Saved",
  },

  platformNames: {
    meta: "Instagram & Facebook",
    google: "Google",
    tiktok: "TikTok",
  } as Record<string, string>,

  common: {
    loading: "Loading…",
    currency: "AED",
  },

  // Creation flow — FLOW §12 strings, used verbatim (binding).
  creation: {
    addTitle: "Add something to advertise",
    addSubtitle: "Paste a link, describe it, or add a list.",
    inputPlaceholder: "Paste a link · or type what you sell…",
    wayLink: "Paste a link",
    wayDescribe: "Describe it",
    wayList: "Add a list",
    listHint: "A spreadsheet or product file, or connect your store.",
    goalLabel: "What do you want from this?",
    goalDefault: "We'll choose the best",
    budgetLabel: "How much per day?",
    budgetDefault: "We'll suggest",
    continue: "Continue",
    reading: "Reading that…",
    linkFailed: "We couldn't open that link. Tell us what you sell instead.",
    fileFailed: "We couldn't read that file. You can describe what you sell, or connect your store instead.",
    disambiguation: "Is this closer to selling a product, or offering a service?",
    disambiguationProduct: "Selling a product",
    disambiguationService: "Offering a service",
    reviewTitle: "Here's the plan",
    reassurance: "We'll start small and put more money behind whatever works.",
    lowBudgetNote:
      "Below about AED 150 a day it's harder for us to learn what works, so results may be slower.",
    yourAds: "Your ads",
    creativeHelp: (n: number): string => `We made ${n}. Keep all, or pick your favorites.`,
    makeNew: "Make new ones",
    editWords: "Change the words",
    preLaunchReassurance: "You can pause or change anything later.",
    launch: "Launch",
    goalLine: "Goal",
    showsOnLine: "Shows on",
    perDayLine: "Per day",
    perDaySuggested: "(suggested)",
    peopleGoToLine: "People go to",
    choose: "Choose",
    connectNote: (name: string): string => `Connect to use ${name}`,
    destinationQuestion: "When someone taps your ad, where should they go?",
    destWebsite: "My website or page",
    destWebsiteHint: "(paste the link)",
    destHostedPage: "A simple page we make for you",
    destHostedForm: "A form we make for you",
    destHostedFormHint: "(collect enquiries)",
    destWhatsapp: "WhatsApp",
    destWhatsappHint: "(chat with you)",
    destCall: "Call you",
    destCallHint: "(tap to call)",
    destHardToMeasure: "Results here are harder to measure precisely; we still track what we can.",
    useThis: "Use this",
    noAccount: "First, choose where to advertise.",
    restrictedNotice:
      "Ads for financial services need a quick check before they go live. We'll handle it and let you know when they're approved — usually within a day.",
    submitForReview: "Submit for review",
    settingUp: "Setting up your ads — this takes a minute.",
    confirmTitle: "You're live.",
    confirmBody: "We're showing your ads and learning what works. You don't need to do anything.",
    reassuranceSmall: "We start small and put more behind what works.",
    spendReassurance: (currency: string, cap: number): string =>
      `We'll never spend more than ${currency} ${cap} a day.`,
    reassuranceTell: "We'll tell you only if we need you.",
    reassurancePause: "You can pause anytime.",
    seeHow: "See how it's doing",
    submittedTitle: "Submitted for review",
    submittedBody: "Submitted — we'll email you when your ads are approved.",
    catalogConfirm: (n: number, currency: string, amount: number): string =>
      `We found ${n} products. We'll advertise them together and show each person the ones they're most likely to buy. About ${currency} ${amount} a day across all of them.`,
    planSentence: (
      title: string,
      goalVerb: string,
      platforms: string,
      currency: string,
      perDay: number,
    ): string =>
      `We'll advertise your ${title} to people likely to ${goalVerb}, on ${platforms}, for about ${currency} ${perDay} a day. We'll start small and put more money behind whatever works.`,
    goalVerbs: {
      best: "respond",
      more_sales: "buy it",
      more_enquiries: "get in touch",
      more_bookings: "book",
      more_app_installs: "install the app",
      more_website_visits: "visit",
    } as Record<string, string>,
  },
};
